baseURL = "https://bryanchen463.github.io/bryan-s-blog/"
languageCode = "zh-cn"
title = "Bryan Chen"
theme = "LoveIt"
publishDir = "public"

[build]
  writeStats = true

[build.archive]
  enable = true

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  description = "Exploring the flow of code & life. Bryan的技术与生活博客"

  [params.author]
    name = "Bryan Chen"

  [params.cdn]
    disable = false

  [params.comment]
    enable = false

  [params.assets]
    customCSS = ["css/custom.css"]
