baseURL = "https://bryanchen463.github.io/bryan-s-blog/"
languageCode = "zh-cn"
title = "Bryan's Blog"
theme = "LoveIt"
publishDir = "public"

[build]
  writeStats = true

[build.archive]
  enable = true

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  description = "Bryan的技术与生活博客"
  author = "Bryan Chen"
